auto: true
pygments: true
docPageNames: [overview, commandline, configuration, controllers, middleware, stylesheets, views]
docPageTitles: [Overview, "Command Line", Configuration, Controllers, Middleware, Stylesheets, Views]
docPageIcons: [home, align-left, check, cogs, wrench, tint, file-alt]